return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    opts = {
        ensure_installed = {
            "python",
            "rust",
            "elixir",
            "c_sharp",
            "typescript",
            "javascript",
            "lua",
            "bash",
            "json",
            "yaml",
            "toml",
            "html",
            "css",
            "markdown",
            "markdown_inline",
            "dockerfile",
            "gitcommit",
            "diff",
            "vim",
            "vimdoc",
        },
    },
}
