describe("devenv-agent", function()
    it("module loads without error", function()
        local ok, mod = pcall(require, "devenv-agent")
        assert.is_true(ok, "devenv-agent module should load: " .. tostring(mod))
        assert.is_table(mod)
    end)

    it("exports expected functions", function()
        local mod = require("devenv-agent")
        assert.is_function(mod.setup)
        assert.is_function(mod.toggle)
        assert.is_function(mod.open)
        assert.is_function(mod.open_visual)
        assert.is_function(mod.set_provider)
    end)

    it("has default config values", function()
        local mod = require("devenv-agent")
        assert.is_table(mod.config)
        assert.is_string(mod.config.provider)
        assert.is_number(mod.config.float_width)
        assert.is_number(mod.config.float_height)
    end)
end)
